//go:build linux

// Code generated by bpf2go; DO NOT EDIT.
// Run `go generate ./ebpf/...` to regenerate from tc_tracker.c.

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

//go:embed tc_tracker.bpf.o
var _BpfBytes []byte

// bpfSpecs holds the ELF section specs parsed from tc_tracker.bpf.o.
type bpfSpecs struct {
	bpfProgramSpecs
	bpfMapSpecs
}

type bpfProgramSpecs struct {
	// TcTracker is the TC egress classifier (SEC("tc")).
	TcTracker *ebpf.ProgramSpec `ebpf:"tc_tracker"`
}

type bpfMapSpecs struct {
	// RttSamples maps backend IPv4 → latest smoothed RTT in microseconds.
	RttSamples *ebpf.MapSpec `ebpf:"rtt_samples"`

	// BytesTx maps backend IPv4 → cumulative egress bytes.
	BytesTx *ebpf.MapSpec `ebpf:"bytes_tx"`

	// Retransmits maps backend IPv4 → cumulative TCP retransmit count.
	Retransmits *ebpf.MapSpec `ebpf:"retransmits"`
}

// bpfObjects holds the loaded eBPF programs and maps after a successful
// loadBpfObjects call. Call Close to release all kernel resources.
type bpfObjects struct {
	bpfPrograms
	bpfMaps
}

func (o *bpfObjects) Close() error {
	return _BpfClose(
		&o.bpfPrograms,
		&o.bpfMaps,
	)
}

type bpfPrograms struct {
	TcTracker *ebpf.Program `ebpf:"tc_tracker"`
}

func (p *bpfPrograms) Close() error {
	return _BpfClose(p.TcTracker)
}

type bpfMaps struct {
	RttSamples  *ebpf.Map `ebpf:"rtt_samples"`
	BytesTx     *ebpf.Map `ebpf:"bytes_tx"`
	Retransmits *ebpf.Map `ebpf:"retransmits"`
}

func (m *bpfMaps) Close() error {
	return _BpfClose(m.RttSamples, m.BytesTx, m.Retransmits)
}

// loadBpfObjects loads tc_tracker.bpf.o into the kernel and populates objs.
// opts may be nil to use defaults.
func loadBpfObjects(objs *bpfObjects, opts *ebpf.CollectionOptions) error {
	spec, err := loadBpf()
	if err != nil {
		return err
	}
	return spec.LoadAndAssign(objs, opts)
}

// loadBpf parses the embedded ELF object into a CollectionSpec.
func loadBpf() (*ebpf.CollectionSpec, error) {
	return loadBpfFromReader(bytes.NewReader(_BpfBytes))
}

func loadBpfFromReader(rd io.ReaderAt) (*ebpf.CollectionSpec, error) {
	spec, err := ebpf.LoadCollectionSpecFromReader(rd)
	if err != nil {
		return nil, fmt.Errorf("can't load bpf: %w", err)
	}
	return spec, nil
}

// _BpfClose closes any combination of closeable resources, returning the
// first non-nil error encountered.
func _BpfClose(closers ...io.Closer) error {
	for _, c := range closers {
		if err := c.Close(); err != nil {
			return err
		}
	}
	return nil
}
